### ISSUE TITLE
Unable to retrieve Instrumentation API to add Paper jar to classpath

### ISSUE THREAD

**Issue by iambenmitchell** [ServerJars/updater#11]
I have attached my console log. This issue has started happening recently.

Start command:                                                                                                     
`java -Xms8G -Xmx8G -jar updater.jar -o true`

Java environment:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

<details closed>
<summary>Console Log</summary>
<br>

ben@letscraft:~/Desktop/teslaTeens$ ./start.sh
   _____                               __
  / ___/___  ______   _____  _____    / /___ ___________
  \__ \/ _ \/ ___/ | / / _ \/ ___/_  / / __ `/ ___/ ___/
 ___/ /  __/ /   | |/ /  __/ /  / /_/ / /_/ / /  (__  )
/____/\___/_/    |___/\___/_/   \____/\__,_/_/  /____/
ServerJars.com           Made with love by Songoda <3

ServerJars is starting...

The jar is up to date.

Launching paper-1.16.5.jar...
..............................

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.songoda.serverjars.ServerJars (file:/home/ben/Desktop/teslaTeens/updater.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of com.songoda.serverjars.ServerJars
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

===========================

Notice: Java has warned you that you are using a workaround if you want to get around this you can add the following arguments: '-Djava.system.class.loader=com.serverjars.updater.ServerJarsLoader'
e.g 'java -Djava.system.class.loader=com.serverjars.updater.ServerJarsLoader -jar serverjars.jar
'Unable to retrieve Instrumentation API to add Paper jar to classpath. If you're running paperclip without -jar then you also need to include the -javaagent:<paperclip_jar> JVM command line option.
ben@letscraft:~/Desktop/teslaTeens$ 

</details>

**Comment by iambenmitchell** [comment]
Looks like this is the same issue as #5

**Comment by toontownlpz** [comment]
Can confirm - this happens to me also.

![image](https://user-images.githubusercontent.com/11021224/121805065-5e2ed480-cc41-11eb-821c-7ef1c41e1b4f.png)


My batch file literally just consists of:
```
@ECHO OFF
title Minecraft 1.16.5 Server
java -jar serverjars-2.jar
pause
```

**Comment by SpraxDev** [comment]
Thanks for your report - A fix will be release in the next update.
