### ISSUE TITLE
InaccessibleObjectException / Java 16 not working

### ISSUE THREAD

**Issue by djnejk** [ServerJars/updater#13]
Hello,
If I start the server using java 16 I getting error
![image](https://user-images.githubusercontent.com/61634734/122473240-db4fa600-cfc1-11eb-97a9-58f592508190.png)

**Comment by SpraxDev** [comment]
Duplicate of #12

A fix is release in the coming week fixing a bunch of stuff (including Java 16).

**Comment by SpraxDev** [comment]
Please download the new updater version. This issue has been fixed
