### ISSUE TITLE
Please Help! When i starting ServerJars, error

### ISSUE THREAD

**Issue by Den4enko** [ServerJars/updater#16]
![image](https://user-images.githubusercontent.com/60628208/123254636-94007280-d4f7-11eb-9bbe-cdf33f5c8033.png)

**Comment by SpraxDev** [comment]
It looks like the API used by the Updater is having some trouble. I've notified somebody so we can hopefully fix it.

**Comment by Den4enko** [comment]
Oh. I see that updater working again!
