### ISSUE TITLE
serverjars-2 doesn't work with Tuinity

### ISSUE THREAD

**Issue by motz0815** [ServerJars/updater#3]
So when using the new serverjars version and tuinity (1.16.4),
the updater crashes almost instantly after starting with this error:
![grafik](https://user-images.githubusercontent.com/49114741/104113012-b6118a00-52f5-11eb-931e-cc55d5c26ed3.png)

**Comment by briannastatic** [comment]
Looks like an issue unique to paper and it's forks. I'll have to have a look at this when I'm back at work Monday.

**Comment by briannastatic** [comment]
Had some time today, wanna try again?

**Comment by motz0815** [comment]
Nice, it works now!
