### ISSUE TITLE
java16

### ISSUE THREAD

**Issue by ghost** [ServerJars/updater#9]
It doesn’t seem to support java16 at the moment. This is very important. Maybe I’m wrong. 
(Google Translate)

**Comment by SpraxDev** [comment]
Can you provide additional information about the trouble you are having? Is it related to #11 or #3

**Comment by SpraxDev** [comment]
Thanks for your report - A fix will be release in the next update.

If you still experience any issues with Java 16, please do not hesitate to reopen the issue.
